## Part 1: Theoretical Questions

<b>1. What are the different data structures used in Tensorflow?. Give some examples.

TensorFlow, a popular deep learning framework, provides several data structures for representing and manipulating data. The main data structures used in TensorFlow are:
Tensor: A tensor is a fundamental data structure in TensorFlow. It is a multi-dimensional array or n-dimensional matrix that represents data. Tensors can be scalars (0-dimensional), vectors (1-dimensional), matrices (2-dimensional), or higher-dimensional arrays. For example, a grayscale image can be represented as a 2D tensor, while a colored image can be represented as a 3D tensor.

Constant: A constant is a specific type of tensor in TensorFlow that holds a fixed value throughout the execution of a program. The value of a constant cannot be changed once it is defined. Constants are commonly used to store hyperparameters or fixed data.

In [1]:
import tensorflow as tf
x = tf.constant([5, 2, 9])
x

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 2, 9])>

Variable: A variable is another type of tensor in TensorFlow that allows the value to be modified during the execution of a program. Variables are used to represent the trainable parameters of a model, such as weights and biases. For example:

In [2]:
w = tf.Variable([6.2, 1.7])
w


<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([6.2, 1.7], dtype=float32)>

Placeholder: In earlier versions of TensorFlow, placeholders were used to feed data into the computation graph during training. However, in TensorFlow 2.x, placeholders have been replaced by the tf.data API and the tf.function decorator. Placeholders are no longer required for most use cases and have been deprecated.

SparseTensor: A sparse tensor is used to efficiently represent tensors with a large number of zero or empty values. It stores only the non-zero elements along with their indices, which helps in reducing memory usage and computational complexity for sparse data.

These data structures are the building blocks of TensorFlow and are essential for creating and manipulating tensors in TensorFlow programs.

<b>Q2. How does the TensorFlow constant differ from a TensorFlow variable? Explain with an example

TensorFlow Constant:
A constant in TensorFlow holds a fixed value throughout the execution of a program.

The value of a constant cannot be changed once it is defined.

Constants are typically used for storing hyperparameters or fixed data that does not need to be modified during training.

Constants are immutable and do not support gradient computations for backpropagation.

Constants can be created using the tf.constant() function.

In [3]:
x = tf.constant([9, 5, 2])


TensorFlow Variable:
A variable in TensorFlow represents a tensor whose value can be modified during the execution of a program.

Variables are commonly used to store the trainable parameters of a model, such as weights and biases.

Variables are mutable and their values can be updated during training using optimization algorithms.

Variables support gradient computations for backpropagation, allowing automatic differentiation and model optimization.

Variables can be created using the tf.Variable() functio

In [4]:
w = tf.Variable([3.6, 9.8,1.2])

In [5]:
print(f"constant : {x.numpy()}")
print(f"variable : {w.numpy()}")

constant : [9 5 2]
variable : [3.6 9.8 1.2]


<b>Q3. Describe the process of matrix addition, multiplication, and element-wise operations in TensorFlow

Matrix Addition:
Matrix addition is performed by adding corresponding elements of two matrices.

The matrices involved in the addition operation must have the same shape (same number of rows and columns).

In TensorFlow, matrix addition is performed using the tf.add() function or the + operator.

The resulting matrix will have the same shape as the input matrices, and each element will be the sum of the corresponding elements from the input matrices.

In [6]:
A = tf.constant([[5, 9], [2, 8]])
B = tf.constant([[8, 6], [9, 3]])

# Matrix addition
Add = tf.add(A, B)

print("Matrix Addition:",Add.numpy())


Matrix Addition: [[13 15]
 [11 11]]


Matrix Multiplication:
Matrix multiplication is performed by multiplying corresponding elements of rows from the first matrix with the corresponding elements of columns from the second matrix and summing the products.

The number of columns in the first matrix must be equal to the number of rows in the second matrix for matrix multiplication to be defined.

In TensorFlow, matrix multiplication is performed using the tf.matmul() function or the @ operator.

The resulting matrix will have a shape of (number of rows in the first matrix, number of columns in the second matrix).

In [7]:
A = tf.constant([[5, 9], [2, 8]])
B = tf.constant([[8, 6], [9, 3]])

# Matrix multiplication
mul = tf.matmul(A, B)

print("Matrix Multiplication:" ,mul.numpy())


Matrix Multiplication: [[121  57]
 [ 88  36]]


Element-wise Operations:
Element-wise operations are performed by applying an operation to corresponding elements of two tensors.

The tensors involved in element-wise operations must have the same shape.

In TensorFlow, element-wise operations are performed using various functions such as tf.add(), tf.subtract(), tf.multiply(), tf.divide(), etc.

The resulting tensor will have the same shape as the input tensors, and each element will be the result of applying the operation to the corresponding elements from the input tensors.

In [8]:
A = tf.constant([4, 2, 0])
B = tf.constant([5, 3, 1])

# Element-wise addition
add = tf.add(A, B)

# Element-wise multiplication
mul = tf.multiply(A, B)

print("Element-wise Addition:")
print(add.numpy())

print("Element-wise Multiplication:")
print(mul.numpy())

Element-wise Addition:
[9 5 1]
Element-wise Multiplication:
[20  6  0]


## Part 2: Practical Implementation

<b>Q1. Create a normal matrix A with dimensions 3x3, using TensorFlow's random_normal function. Display the values of matrix A


In [9]:
A  = tf.random.normal(shape=(3,3))
A.numpy()

array([[-0.33042693, -0.6109597 ,  1.9144475 ],
       [ 0.91158545, -0.95501786, -0.4260239 ],
       [ 0.48540348, -0.98570657,  0.47623232]], dtype=float32)

<b>Q2. Create a Gaussian matrix B with dimensions 4x4, using TensorFlow's truncated_normal function. Display the values of matrix B

In [10]:
B = tf.random.truncated_normal(shape=(4, 4))
B.numpy()

array([[-1.0053284 , -1.7478458 , -0.16219774, -0.70874345],
       [-0.20832811, -0.0351022 , -0.20884034, -0.67297107],
       [-0.82128143, -0.1993792 , -0.12198337, -0.78588915],
       [ 0.03800399,  1.8095676 , -0.4332796 ,  0.1822889 ]],
      dtype=float32)

<b>Q3 3. Create a matrix C with dimensions 2x2, where the values are drawn from a normal distribution with a mean of 3 and a standard deviation of 0.5, using TensorFlow's random.normal function. Display the values of matrix C.

In [11]:
C = tf.random.normal(shape=(2, 2), mean=3, stddev=0.5)
C.numpy()

array([[3.5904498, 3.766258 ],
       [2.6235225, 2.8164082]], dtype=float32)

<b>Q4  Perform matrix addition between matrix A and matrix B, and store the result in matrix D

In [12]:
A = tf.constant([[5, 9], [2, 8]])
B = tf.constant([[8, 6], [9 ,3]])
D = tf.add(A,B)
D.numpy()

array([[13, 15],
       [11, 11]])

<b>Q5. Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E

In [13]:
C = tf.constant([[5, 9], [2, 8]])
D = tf.constant([[8, 6], [9 ,3]])

E = tf.matmul(C,D)
E.numpy()

array([[121,  57],
       [ 88,  36]])

## Task 2:


<b>Q1. Create a matrix F with dimensions 3x3, initialized with random values using TensorFlow's random_uniform function.

In [14]:
F = tf.random.uniform(shape=(3, 3))
F.numpy()

array([[0.47360432, 0.76139164, 0.8667531 ],
       [0.22871578, 0.03727865, 0.11786652],
       [0.25199342, 0.975832  , 0.00415921]], dtype=float32)

<b>Q2. Calculate the transpose of matrix F and store the result in matrix G.


In [15]:
G = tf.transpose(F)
G
G.numpy()

array([[0.47360432, 0.22871578, 0.25199342],
       [0.76139164, 0.03727865, 0.975832  ],
       [0.8667531 , 0.11786652, 0.00415921]], dtype=float32)

<B>Q3. Calculate the element-wise exponential of matrix F and store the result in matrix H.

In [16]:
H = tf.exp(F)
H.numpy()

array([[1.6057715, 2.141254 , 2.3791733],
       [1.2569847, 1.0379822, 1.1250939],
       [1.2865876, 2.653374 , 1.0041679]], dtype=float32)

<b>Q4. Create a matrix I by concatenating matrix F and matrix G horizontally.

In [17]:
I = tf.concat([F, G], axis=1)
I.numpy()

array([[0.47360432, 0.76139164, 0.8667531 , 0.47360432, 0.22871578,
        0.25199342],
       [0.22871578, 0.03727865, 0.11786652, 0.76139164, 0.03727865,
        0.975832  ],
       [0.25199342, 0.975832  , 0.00415921, 0.8667531 , 0.11786652,
        0.00415921]], dtype=float32)

<B>Q5. Create a matrix J by concatenating matrix F and matrix H vertically.


In [18]:
J = tf.concat([F,H],axis = 0)
J.numpy()

array([[0.47360432, 0.76139164, 0.8667531 ],
       [0.22871578, 0.03727865, 0.11786652],
       [0.25199342, 0.975832  , 0.00415921],
       [1.6057715 , 2.141254  , 2.3791733 ],
       [1.2569847 , 1.0379822 , 1.1250939 ],
       [1.2865876 , 2.653374  , 1.0041679 ]], dtype=float32)